<?php
/**
* @var $block \Magelearn\SimpleNote\Block\Adminhtml\Order\View\Tab\SimpleNote
*/
?>

<div class="fieldset-wrapper order-information">
   <div>
       <h2>Simple Note</h2>
   </div>
   <div class="fieldset-wrapper-title">
       <span class="title"><?php /* @escapeNotVerified */
           echo __("Information for Order's Simple note") ?></span>
   </div>
   <table class="admin__table-secondary">
       <tbody>
       <?php echo $block->getChildHtml(); ?>
       <tr>
           <th><?php /* @escapeNotVerified */
               echo __('Order ID:') ?></th>
           <td><?php echo $block->getOrderIncrementId(); ?></td>
       </tr>
       <tr>
           <th><?php /* @escapeNotVerified */
               echo __('Order Simple Note:') ?></th>
           <td><?php echo $block->getSimpleNote(); ?></td>
       </tr>
       </tbody>
   </table>
</div>